### PR TITLE
CLUE Metal Detector in CircuitPython - minor code update

### PR DESCRIPTION
**Pull request by kevinjwalters**
A very minor update:

- Fixing a bug when running on a CPB (CLUE is the main platform).
- Consistency on case on the intro `Button Guide` screen.

I think @cogliano approved last one, actually I see @ladyada did it for #1100

### CODE REVIEW

**Comment by kevinjwalters** [comment]
A curious error reported by Travis in https://travis-ci.com/github/adafruit/Adafruit_Learning_System_Guides/builds/164811414. And, for once, it's not me but some problem with `esp8266` builds.

The dns messages _may_ be a _red herring_.

```
########################################################################

SWITCHING TO esp8266: ✓

########################################################################

tpl5111demo.ino: ✖

----------------------------- DEBUG OUTPUT -----------------------------

Picked up JAVA_TOOL_OPTIONS: 

Set log4j store directory /home/travis/.arduino15

Loading configuration...

Initializing packages...

Preparing boards...

Invalid library found in /home/travis/arduino_ide/libraries/Adafruit_Test_Library: no headers files (.h) found in /home/travis/arduino_ide/libraries/Adafruit_Test_Library

Invalid library found in /home/travis/arduino_ide/libraries/Adafruit_Test_Library: no headers files (.h) found in /home/travis/arduino_ide/libraries/Adafruit_Test_Library

Verifying...

[SocketListener(travis-job-b0b82c89-985b-4534-af26-75a02bfb6faa-c-travis-ci-prod-3-internal.local.)] WARN javax.jmdns.impl.DNSIncoming$MessageInputStream - Bad domain name: possible circular name detected. Bad offset: 0x3fff at 0x71

[SocketListener(travis-job-b0b82c89-985b-4534-af26-75a02bfb6faa-c-travis-ci-prod-3-internal.local.)] WARN javax.jmdns.impl.constants.DNSRecordType - Could not find record type for index: 65535

[SocketListener(travis-job-b0b82c89-985b-4534-af26-75a02bfb6faa-c-travis-ci-prod-3-internal.local.)] WARN javax.jmdns.impl.DNSIncoming - Could not find record type: dns[query,10.30.1.187:5353, length=115, id=0x0]

   0: 0000000000010000 000100004b747261 7669732d6a6f622d 6230623832633839     ........ ....Ktra vis-job- b0b82c89

  20: 2d393835622d3435 33342d616632362d 3735613032626662 366661612d632d74     -985b-45 34-af26- 75a02bfb 6faa-c-t

  40: 72617669732d6369 2d70726f642d332d 696e7465726e616c 056c6f63616c0000     ravis-ci -prod-3- internal .local..

  60: ff0001c00c000100 010000000a00040a 1e01bb                                ........ ........ ...

[SocketListener(travis-job-b0b82c89-985b-4534-af26-75a02bfb6faa-c-travis-ci-prod-3-internal.local.)] WARN javax.jmdns.impl.constants.DNSRecordClass - Could not find record class for index: 65535

[SocketListener(travis-job-b0b82c89-985b-4534-af26-75a02bfb6faa-c-travis-ci-prod-3-internal.local.)] WARN javax.jmdns.impl.DNSIncoming$MessageInputStream - Bad domain name: possible circular name detected. Bad offset: 0x3fff at 0x71

[SocketListener(travis-job-b0b82c89-985b-4534-af26-75a02bfb6faa-c-travis-ci-prod-3-internal.local.)] WARN javax.jmdns.impl.constants.DNSRecordType - Could not find record type for index: 65535

[SocketListener(travis-job-b0b82c89-985b-4534-af26-75a02bfb6faa-c-travis-ci-prod-3-internal.local.)] WARN javax.jmdns.impl.DNSIncoming - Could not find record type. domain: 

dns[query,10.30.1.187:5353, length=115, id=0x0, questions=1

questions:

	[DNSQuestion@924206180 type: TYPE_IGNORE index 0, class: CLASS_UNKNOWN index 0, name: job-b0b82c89-985b-4534-af26-75a02bfb6faa-c-tr.ci-prod-3-internallocalϰ



ο.]]

	question:      [DNSQuestion@924206180 type: TYPE_IGNORE index 0, class: CLASS_UNKNOWN index 0, name: job-b0b82c89-985b-4534-af26-75a02bfb6faa-c-tr.ci-prod-3-internallocalϰ



ο.]

   0: 0000000000010000 000100004b747261 7669732d6a6f622d 6230623832633839     ........ ....Ktra vis-job- b0b82c89

  20: 2d393835622d3435 33342d616632362d 3735613032626662 366661612d632d74     -985b-45 34-af26- 75a02bfb 6faa-c-t

  40: 72617669732d6369 2d70726f642d332d 696e7465726e616c 056c6f63616c0000     ravis-ci -prod-3- internal .local..

  60: ff0001c00c000100 010000000a00040a 1e01bb                                ........ ........ ...

[SocketListener(travis-job-b0b82c89-985b-4534-af26-75a02bfb6faa-c-travis-ci-prod-3-internal.local.)] WARN javax.jmdns.impl.constants.DNSRecordClass - Could not find record class for index: 65535

[SocketListener(travis-job-b0b82c89-985b-4534-af26-75a02bfb6faa-c-travis-ci-prod-3-internal.local.)] WARN javax.jmdns.impl.DNSIncoming - Could not find record class. domain:  type: TYPE_IGNORE index 0

dns[query,10.30.1.187:5353, length=115, id=0x0, questions=1

questions:

	[DNSQuestion@924206180 type: TYPE_IGNORE index 0, class: CLASS_UNKNOWN index 0, name: job-b0b82c89-985b-4534-af26-75a02bfb6faa-c-tr.ci-prod-3-internallocalϰ



ο.]]

	question:      [DNSQuestion@924206180 type: TYPE_IGNORE index 0, class: CLASS_UNKNOWN index 0, name: job-b0b82c89-985b-4534-af26-75a02bfb6faa-c-tr.ci-prod-3-internallocalϰ



ο.]

   0: 0000000000010000 000100004b747261 7669732d6a6f622d 6230623832633839     ........ ....Ktra vis-job- b0b82c89

  20: 2d393835622d3435 33342d616632362d 3735613032626662 366661612d632d74     -985b-45 34-af26- 75a02bfb 6faa-c-t

  40: 72617669732d6369 2d70726f642d332d 696e7465726e616c 056c6f63616c0000     ravis-ci -prod-3- internal .local..

  60: ff0001c00c000100 010000000a00040a 1e01bb                                ........ ........ ...

fork/exec /bin/xtensa-lx106-elf-g++: no such file or directory

------------------------------------------------------------------------

```

**Comment by jepler** [comment]
The actual error was 
> fork/exec /bin/xtensa-lx106-elf-g++: no such file or directory
Last time something like this came up, I determined it was apparently travis's cache that had wrong content.  Since it's now happened at least twice in quick succession, maybe somebody should look into it?  But for now, I've cleared the cache and requested the build to re-run.

**Comment by kevinjwalters** [comment]
@jepler Thanks. I'll listen to https://www.youtube.com/watch?v=PXatLOWjr-k while it builds...

**Comment by kevinjwalters** [comment]
A good spot. I think the reason it ended up that way is partly because it turned out the mangetomer is very stable at the resolution presented on screen and I added the recalibration late in the development. The biggest issue there is that it's only the z value to allow user to spin it but tilting it also knocks value around a fair bit.

**Pull request merged**
