### PR TITLE
Add NeXT to USB adapter with CircuitPython & RP2040

### PR DESCRIPTION
**Pull request by jepler**
In 2012, Lady Ada wrote a Learn project to convert a NeXT keyboard to USB with an Arduino Micro.

Now, ten years later, the keyboard is still as awesome as ever!  So awesome that for the anniversary we re-did the project with our favorite environment (CircuitPython) and an awesome microcontroller (RP2040)

In draft state for the moment, as I'm going to move the project from the Adafruit Feather RP2040 to the Adafruit QT Py RP2040 instead! It also doesn't handle sending vertical bar or backslash keys as those are in non-standard shifted locations.

This pull request text was typed on the NeXT keyboard!

### CODE REVIEW

**Comment by TheKitty** [comment]
Please add SPDX

**Comment by TheKitty** [comment]
Per Slack, waiting until review requested

**Comment by jepler** [comment]
@TheKitty Ready for your review!

**Review by kattni — APPROVED** [review]
Looks good to me!

**Pull request merged**
