### PR TITLE
Update comment.

### PR DESCRIPTION
**Pull request by kattni**
Clarify what `loop` means in playing a `RawSample`.

### CODE REVIEW

**Comment by ladyada** [comment]
@kattni i can approve once linty :)

**Comment by kattni** [comment]
@ladyada This isn't a lint issue, it's failing on some Arduino code. I restarted the build once, and it failed the same.

**Comment by ladyada** [comment]
@kattni what do ya do when you have a travis CI build fail on arduino code?

**Comment by kattni** [comment]
@ladyada Wipe the caches? At least that's the only bell that question is ringing in my mind. I'm not sure I've ever done it. Clicked "Caches" under settings and see a "Delete all respository caches" link at the top. Is that correct?

**Comment by ladyada** [comment]
yes try it!

**Comment by kattni** [comment]
Rerunning build.

**Comment by kattni** [comment]
@ladyada Passed finally.

**Pull request merged**
