### PR TITLE
fix audio calls to be compatible with CP5.0 audiocore

### PR DESCRIPTION
**Pull request by jerryneedell**
Also backward compatible with CP 4.1.0
Tested on PyPortal with CP4.1.0 and current master 5.0.0-alpha.0-154-gbe52025d02

### CODE REVIEW

**Comment by jerryneedell** [comment]
pylint complained about this: can anyone tell me how to fix it?
```
Minesweep/code.py 24: Imports from package audioio are not grouped (ungrouped-imports)
```

**Comment by ladyada** [comment]
thats.. a new one :/

**Comment by jerryneedell** [comment]
I think I found it  -- trying again

**Comment by jerryneedell** [comment]
If this fix is acceptable, it needs someone with permission to review/merge.

**Comment by ladyada** [comment]
approved based on daves check!

**Pull request merged**
