### PR TITLE
Updated Slideshow_Soundtrack to run on both HalloWing M0 and M4

### LINKED ISSUE #846: Slideshow Soundtrack Error
Testing **slideshows_slideshow.py** code for the TinyMuseumTour Learn guide on HalloWing M4 running Circuit Python 5 Alpha 4. REPL throws error:

`code.py output:
Traceback (most recent call last):
  File "code.py", line 7, in <module>
  File "adafruit_slideshow.py", line 200, in __init__
  File "adafruit_slideshow.py", line 323, in advance
AttributeError: 'Display' object has no attribute 'wait_for_frame'`

Learn guide:
https://learn.adafruit.com/tiny-museum-tour-device/code-with-circuitpython

github code:
https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/master/Slideshows_Soundtrack/slideshows_soundtrack.py

### PR DESCRIPTION
**Pull request by makermelissa**
Please note that TOUCH1-TOUCH4 and SPEAKER alias pins were recently pushed to the HALLOWING M4 (today) and until the next release of CircuitPython may need to be adjusted manually. I tested with a speaker on both the HalloWing M0 and M4. Also, images are smaller on the M4 due to the higher resolution screen.

Fixes #846.

### CODE REVIEW

**Comment by ladyada** [comment]
rad! @djecken try dis!

**Comment by djecken** [comment]
Tested latest slideshow code on HalloWing M4 running circuit python 5, from absolute latest adafruit-circuitpython-hallowing_m4_express-en_US-20190919-76d463e.uf2

Needed to change **speaker** to **A0** in order for it to work on HalloWing M4:
`a = audioio.AudioOut(board.A0)`

Audio out has a lot of noise, it's pretty consistent. Using mini oval speaker direct plugged into pico connector. Not sure if this is a hardware problem?

**Comment by makermelissa** [comment]
Yeah, there was some noise for me. Holding the speaker helped as I think it was buzzing against the desk and it was the same on both the M0 and M4. 

As for SPEAKER the PR is still waiting in a queue for CP.

**Comment by djecken** [comment]
Interesting, audio clips with smaller file sizes do not generate extra noise – for example, the mario jump sound and badge chirp do not have any noise and sound crisp and clean.

**Pull request merged**
