### PR TITLE
ArduinoSelfTest for PyPortal Titano

### PR DESCRIPTION
**Pull request by gmeader**
Code from Pyportal ArduinoSelfTest altered to support the larger HX8357 display on the Titano. 
Also more pleasant audio file.

### CODE REVIEW

**Comment by ladyada** [comment]
@makermelissa wanna look and try to fix up CI?

**Comment by makermelissa** [comment]
It appears to be failing because the .ino file and the folder are different names.

**Comment by ladyada** [comment]
@makermelissa dunno if you can push to the branch, maybe easier to hand-commit anew?

**Comment by makermelissa** [comment]
I'll give both a try.

**Comment by makermelissa** [comment]
Pushing to the branch worked.

**Review by makermelissa — APPROVED** [review]
Looks good to me.

**Pull request merged**
