### PR TITLE
adding try/except to DVI hello world

### PR DESCRIPTION
**Pull request by BlitzCityDIY**
Adding a try/except to workaround a MemoryError in CircuitPython 9 beta2 as noted in https://github.com/adafruit/Adafruit_Learning_System_Guides/issues/2746

### CODE REVIEW

**Comment by TheKitty** [comment]
I do think it'd be good for someone to look at the root cause first before trying to catch the error unless this is a stopgap.

cc @dhalbert @tannewt

**Comment by FoamyGuy** [comment]
I found that the example seems to run successfully on the 1st attempt if the initialization is changed to be like this:
```
# check for DVI Feather with built-in display
if 'DISPLAY' in dir(board):
    display = board.DISPLAY

# check for DVI feather without built-in display
elif 'CKP' in dir(board):
    displayio.release_displays()
    fb = picodvi.Framebuffer(320, 240,
        clk_dp=board.CKP, clk_dn=board.CKN,
        red_dp=board.D0P, red_dn=board.D0N,
        green_dp=board.D1P, green_dn=board.D1N,
        blue_dp=board.D2P, blue_dn=board.D2N,
        color_depth=8)
    display = framebufferio.FramebufferDisplay(fb)
# otherwise assume Pico
else:
    displayio.release_displays()
    fb = picodvi.Framebuffer(320, 240,
        clk_dp=board.GP12, clk_dn=board.GP13,
        red_dp=board.GP10, red_dn=board.GP11,
        green_dp=board.GP8, green_dn=board.GP9,
        blue_dp=board.GP6, blue_dn=board.GP7,
        color_depth=8)
    display = framebufferio.FramebufferDisplay(fb)
```
Basically it will just check for `board.DISPLAY` first and use that if it exists and only if not then attempt to init a display. 

My best guess is perhaps there was some period of time when the device support CircuitPython but didn't have `board.DISPLAY` automatically initialized in the core yet, and that this example (and perhaps more) was created during that time in which it would have been necessary to init the display before showing anything on it.

**Comment by BlitzCityDIY** [comment]
this was early code, right at the release of the board so that makes sense. when i add that check for `board.DISPLAY` i initially got an error for `bitmap = displayio.Bitmap(display.width, display.height, 3)`:

```
Traceback (most recent call last):
  File "code.py", line 53, in <module>
AttributeError: 'NoneType' object has no attribute 'width'
```

i hard coded those (`320, 240`), but then get this error for `display.root_group = group`:
```
Traceback (most recent call last):
  File "code.py", line 331, in <module>
AttributeError: can't set attribute 'root_group'
```

**Comment by FoamyGuy** [comment]
To fix this error:
```
Traceback (most recent call last):
  File "code.py", line 53, in <module>
AttributeError: 'NoneType' object has no attribute 'width'
```
You need to remove the `displayio.release_displays()` from the top of the script. It should only be inside of the elif and else now. (Sorry I didn't mention that in my prior post).

I think the second error is likely related to this as well, but I'm not as certain on that one. 

Make this change to remove that line from the top, then unplug / re-plug once after you've saved the new code and see if you still have any errors after that.

**Comment by FoamyGuy** [comment]
I tested this PR version succesfully on the Feather DVI with 9.0.0 beta.2

We can still let Scott or Dan chime in for final approval, but this looks good to me.

The fact that after `release_displays()` there is not enough memory to re-initialize the display sounds like a potential bug to me, but I'm not certain of it. And if it is, I do think it's a separate issue and this fix does still stand on it's own as an improvement.

**Comment by tannewt** [comment]
> I do think it'd be good for someone to look at the root cause first before trying to catch the error unless this is a stopgap.
> 
> cc @dhalbert @tannewt

Thanks @TheKitty. It was a bug in CP. It is good to just not work around it.

> We can still let Scott or Dan chime in for final approval, but this looks good to me.

I think this change to use `board.DISPLAY` when available is good. Any reloading would be suspect to me.

> The fact that after `release_displays()` there is not enough memory to re-initialize the display sounds like a potential bug to me, but I'm not certain of it. And if it is, I do think it's a separate issue and this fix does still stand on it's own as an improvement.

Yup, it was. The next 9.0.0 release should have a fix for it. https://github.com/adafruit/circuitpython/pull/9004

**Comment by BlitzCityDIY** [comment]
just to check- i know this ended up being a CP issue but the change here to check for `board.DISPLAY` now that that is in the Feather DVI board def should still be added for this example?

**Review by FoamyGuy — APPROVED** [review]
Yes, it should get this check for sure. Scott mentioned that as well. 

There is no reloading left in the code either. This change looks good to me. Thanks for the fix @BlitzCityDIY

**Pull request merged**
