### PR TITLE
Adding files lego head

### PR DESCRIPTION
**Pull request by djecken**
Add files lego head

### CODE REVIEW

**Comment by ladyada** [comment]
@djecken do you know how to lint on your computer?

**Comment by djecken** [comment]
I just look at the job log and read through the comments. this one looks like it just needs a new line at the end.

**Comment by ladyada** [comment]
please follow this guide https://learn.adafruit.com/improve-your-code-with-pylint

**Comment by djecken** [comment]
will do, brb installing python3 =D

**Comment by ladyada** [comment]
itll save you time in the long run!!!

**Pull request merged**
