### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by jedgarpark**
Funhouse door alert code

### CODE REVIEW

**Review by makermelissa — COMMENTED** [review]
Rather than saving door_value in an external variable, you could pass a parameter to send_io_data() with the value.

**Comment by jedgarpark** [comment]
@makermelissa the door_value is True or False and AIO want 0 or 1.

**Comment by makermelissa** [comment]
You're already sending door_value via MQTT. My suggestions was to make the function:
```
def send_io_data(door_value):
    funhouse.peripherals.led = True
    print("Sending data to adafruit IO!")
    funhouse.network.mqtt_publish("door", door_value)
    funhouse.peripherals.led = False
```
and then just call
`send_io_data(1)` or `send_io_data(0)`

However, you can convert True or False to 1 or 0 with int().

**Comment by jedgarpark** [comment]
Ah, I see. I'll make that change, thanks @makermelissa

**Review by makermelissa — APPROVED** [review]
Looks good to me

**Pull request merged**
