### PR TITLE
PyPortal Trivia Time

### PR DESCRIPTION
**Pull request by isaacwellish**
Remade the branch, should just contain this project now

### CODE REVIEW

**Comment by ladyada** [comment]
i refactored this code - please spend an hour tomorrow looking at the differences

[code.txt](https://github.com/adafruit/Adafruit_Learning_System_Guides/files/3395025/code.txt)

**Comment by isaacwellish** [comment]
Ok thanks for refactoring! Added a timer display so user(s) knows when timer starts and for how long. Additionally added some other tweaks.

**Comment by ladyada** [comment]
ok try making the bitmaps monochrome. they seem to be just black and white anyways and that will speed up loading

**Comment by isaacwellish** [comment]
just made the bitmaps monochrome and that definitely sped things up!

**Comment by tannewt** [comment]
Are you running this on the 4.1.0 beta? That will also speed it up.

**Comment by isaacwellish** [comment]
@tannewt yup! Speeds it up a ton. I also put a warning in the guide for people to use 4.1.0 beta. Great work on it!

**Pull request merged**
