### PR TITLE
Dev/fix-logging-changes

### PR DESCRIPTION
**Pull request by tekktrik**
Updates Learn example code to account for `adafruit_logging>=4.1.0` which now requires the `StreamHandler` to be attached to `Logger` instances.

Changed the "A Logger for CircuitPython" how-to into an example for using the file handler provided in `adafruit_logging` (`FileHandler`).

Some updates required to the guides, mostly to the "A Logger for CircuitPython" guide, and most of these are minor (except for the change of one "guide" to an "example")

Did not test.

### CODE REVIEW

**Comment by ladyada** [comment]
@dastels please look

**Review by dastels — APPROVED** [review]
LGTM

**Comment by tekktrik** [comment]
Small update to fix the `pylint` error, no content changed since approval.  Happy to help with changes to the Learn Guides as needed.

**Comment by tekktrik** [comment]
@dastels mind re-approving?

**Review by dastels — APPROVED** [review]

**Review by ladyada — APPROVED** [review]

**Pull request merged**
