### PR TITLE
Corrected spelling errors, rearranged code for readability, and simpl…

### PR DESCRIPTION
**Pull request by leftrightthere**
Corrected spelling errors, rearranged code for readability, and simplified many operations.

I maintained the purpose of the script which is functionality and examples of the features available.
Code was tested on PyPortal (https://www.adafruit.com/product/4116)

Global constants were placed at the top.
Methods were moved above dynamic code.
Functions pass in variables rather than using global values.
Added some comments to explain why a value is used and how it works.

### CODE REVIEW

**Comment by ladyada** [comment]
@FoamyGuy the original author wont be reviewing so maybbe you can look/test!

**Comment by dhalbert** [comment]
Could you run the code through `black`, which may reformat it from what you did? In particular the extra spaces you added to line up columns may be removed. We mostly adhere to `black` as a code formatting standard.

**Review by FoamyGuy — APPROVED** [review]
Looks good to me. Thanks for working on this @leftrightthere. 

I pushed one more commit with minor changes to use string.format() instead of percent formatting in a few places, and to rename the variables with "TAPS" in the name to be more descriptive e.g. `TAB_BUTTON_Y` etc.. also to help avoid accidental confusion between TAP and TAB within the variable names of the code.

I tested the new version successfully on PyPortal and PyPortal Titano.

**Comment by FoamyGuy** [comment]
I've updated the relevant sections within the learn guide with regards to the bits of code that have been tweaked.

**Pull request merged**
