### PR TITLE
PyPortal ViewMaster

### PR DESCRIPTION
**Pull request by djecken**
Pyportal viewmaster files

### CODE REVIEW

**Comment by djecken** [comment]
@TheKitty hiya can you please take a look at the build log for a potential fix? thanks!

**Comment by TheKitty** [comment]
Ok, it's not pretty but not impossible.

**Comment by djecken** [comment]
much appreicated @TheKitty ! are there any resources I can look at for proper pylinting? I can just barely decipher what the errors/warnings mean in the failed build log. Reminds me of my days validating HTML/CSS.

**Comment by TheKitty** [comment]
I fixed some of it but the line ending issue is elusive. I sent an email to others cc you asking for help.

**Comment by ladyada** [comment]
use `dos2unix`

**Comment by TheKitty** [comment]
Limor, it's complaining about the exception checking being too general. I tried to just catch all but it still doesn't like it
PyPortal_ViewMaster/viewmaster.py 23: Catching too general exception Exception (broad-except)

**Pull request merged**
