### PR TITLE
Added Home Assistant Sensor project code

### PR DESCRIPTION
**Pull request by makermelissa**
Code for my Home Assistant guide

### CODE REVIEW

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
maybe makes sense to go into deep sleep when done? i think people would like that!

**Comment by makermelissa** [comment]
Oh right, I forgot it could do that. I'll see if I can get that working.

**Comment by makermelissa** [comment]
I modified it for deep sleep and am running into this bug: https://github.com/adafruit/circuitpython/issues/4079 so it basically stops working after waking up.

**Comment by makermelissa** [comment]
I decided to give users the option for when it does get fixed.

**Pull request merged**
