### PR TITLE
Add PyBadge Conference Badge Code

### PR DESCRIPTION
**Pull request by makermelissa**
Adding Files for Multi-Language PyBadge Conference Badge Nametag

### CODE REVIEW

**Comment by ladyada** [comment]
hmm we'd prefer not to add submodules - either the code should go in as-is or we can make a new repo if its a big project!

**Comment by makermelissa** [comment]
Oops, I didn’t mean to submit it as a submodule. It must have been automatic because I copied the folder from another repo. I’ll fix.

**Comment by makermelissa** [comment]
Ok, I think I got it fixed now. Thanks.

**Comment by ladyada** [comment]
ok u can merge once travis passes!

**Comment by makermelissa** [comment]
Oh, it passed, but it doesn't look like I have merging permissions for this repo.

**Pull request merged**
