### PR TITLE
Fix date time parsing + Y offset

### PR DESCRIPTION
**Pull request by bergdahl**
Date parsing failed for time zones with positive offsets, like Europe/Stockholm. 
I rewrote the parsing to use substrings instead of split. Also, the text was off screen in the Y direction, so I moved it down to be visible.

### CODE REVIEW

**Comment by ladyada** [comment]
hihi can you check, there's a new version that got merged first (with text update) which makes this have conflicts. you may want to 'start fresh'

**Comment by bergdahl** [comment]
I merged the changes, do I need to make a new pull request? And yes, I am new to this. :-)

**Comment by ladyada** [comment]
nope - just need someone to test em! :)

**Review by FoamyGuy — APPROVED** [review]
This looks good to me. The old code broke with `Europe/Stockholm` due to the `+` near the end. 
The new code ignores the seconds decimal value and no longer breaks with timezones that are `+` from UTC. It uses index within the string to break it down into components.

Tested successfully on a device, `Europe/Stockholm` now shows correctly instead of raising error.

Thanks for working on this @bergdahl!

**Comment by ladyada** [comment]
thanks for testing + fixing -

**Pull request merged**
