### PR TITLE
Update Snow_Globe_BLE_CPB for CP 5.0 Beta _bleio

### PR DESCRIPTION
**Pull request by jerryneedell**
Updated for new API
revised the way advertising is started/restarted  to avoid errors
also set the  default shake threshold to 20 ( was 27 and hard to get it to respond)
Tested on CPB

### CODE REVIEW

**Comment by jerryneedell** [comment]
hmm any suggestion s on how to fix this ```319.45s$ ./pylint_check
1135Using config file /home/travis/build/jerryneedell/Adafruit_Learning_System_Guides/.pylintrc
1136************* Module ble_snowglobe
1137Snow_Globe_BLE_CPB/ble_snowglobe.py 51: Access to a protected member _adapter of a client class (protected-access)
1138
1139------------------------------------
1140Your code has been rated at 10.00/10
1141
1142The command "./pylint_check" exited with 123.
114365.45s$ build_main_platforms
1144
1145
```

**Comment by dhalbert** [comment]
@jerryneedell Add `#pylint: disable=protected-access` to the offending line.

**Comment by dhalbert** [comment]
Try putting the `#pylint:` as a comment on the same line. That will restrict the scope to that line.

**Comment by dhalbert** [comment]
you can try running pylint locally :)

**Comment by jerryneedell** [comment]
Sorry -- When I do I get lots of error for Guides , but I may just need to re-install it.

**Comment by jerryneedell** [comment]
Travis keep failing well beyond the pylint checks -- please let me know what I can do to fix it.

**Comment by ladyada** [comment]
@dhalbert @jerryneedell when you see these errors you need to delete travis caches

**Pull request merged**
