### PR TITLE
Add code for Trinkey QT2040 TRNG

### PR DESCRIPTION
**Pull request by caternuson**
Arduino sketch is the main code. Python code provides simple usage examples.

### CODE REVIEW

**Comment by TheKitty** [comment]
You need a .test.only file
See https://learn.adafruit.com/submitting-arduino-code-to-the-adafruit-learning-system/adding-a-test-only-file

**Comment by TheKitty** [comment]
Looks like 
/home/runner/Arduino/libraries/OPTIGA_Trust_M/src/optiga_trustm/pal_logger_arduino.cpp: In function 'pal_status_t pal_logger_read(void*, uint8_t*, uint32_t)':
/home/runner/Arduino/libraries/OPTIGA_Trust_M/src/optiga_trustm/pal_logger_arduino.cpp:71:1: **error: no return statement in function returning non-void** [-Werror=return-type]

**Comment by caternuson** [comment]
i think we're gonna need a release from infineon:
https://github.com/Infineon/arduino-optiga-trust-m/pull/8#issuecomment-988318864

**Comment by ladyada** [comment]
change the test to be some other platform that doesnt treat warnings as errors

**Comment by caternuson** [comment]
huzzah! using manual lib did the trick. removed changes to `library.deps` and changed test back to `.qt2040_trinkey.test.only`.

**Comment by TheKitty** [comment]
Ready to merge @caternuson ?

**Review by ladyada — APPROVED** [review]

**Pull request merged**
