### PR TITLE
Reorganized directory

### PR DESCRIPTION
**Pull request by dherrada**

### CODE REVIEW

**Review by kattni — COMMENTED** [review]
Should `feather_code.py` be `code.py` or is it that way for a reason?

**Comment by dherrada** [comment]
@kattni Yeah, it's that way for a reason. That example uses 2 devices so I thought it'd be less confusing if one was named so it was clear it was for the neopixel controller and not the pyportal remote

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
@dherrada please rebase to fix up CI :)

**Comment by dherrada** [comment]
Uhh I did not do that right lol. Fixing

**Pull request merged**
