### PR TITLE
eInk FeatherWing demo code

### PR DESCRIPTION
**Pull request by djecken**
eInk FeatherWing demo code

### CODE REVIEW

**Comment by TheKitty** [comment]
Somehow the code now has each line terminated by a carriage return and line feed when it expects only a line feed. There is a 3rd party utility, dos2unix (command line) that fixes this.

**Comment by TheKitty** [comment]
The line endings are still the same. You also need a blank line at the end of the file.

I had this same issue a couple weeks ago. It's a pain.

**Comment by djecken** [comment]
thanks, looking up found a resource. any tips on the formatting options would be very helpful

[https://www.computerhope.com/unix/dos2unix.htm](url)

**Comment by TheKitty** [comment]
Looks like you got all of them except 4 lines

**Comment by djecken** [comment]
OK another try – BTW I'm using using mac os TextEdit app. Just hitting delete and enter key for every line ¯\_(ツ)_/¯

**Comment by ladyada** [comment]
@djecken you can use `dos2unix`

**Comment by djecken** [comment]
thanks for the tip with dos2unix @TheKitty @ladyada this worked out

**Pull request merged**
