### PR TITLE
Examples for new esp32_camera module in CircuitPython 8

### PR DESCRIPTION
**Pull request by jepler**
These need more polish and the guide is yet to be started, so it's created in draft mode.

### CODE REVIEW

**Comment by TheKitty** [comment]
Some import issues

**Review by TheKitty — COMMENTED** [review]
@jepler - is there a reason the license type is "Unlicense" rather than "MIT"?

**Comment by jepler** [comment]
> @jepler - is there a reason the license type is "Unlicense" rather than "MIT"?

not sure why. I started with a copy of a copy of a file with the copyright style in the boilerplate I used. There are about 44 "unlicense"'d files in learn currently, but I can change it to MIT if that's the standard.

**Comment by jepler** [comment]
Especially as RedHat has decided that CC0 also called the Unlicense is not suitable for "open source" computer code [see https://hackaday.com/2022/07/29/why-fedora-decided-to-give-cc0-licensed-code-the-boot/ and other discussions] I think it's good to fix this and maybe check the authorship on the other 4 dozen files to see if adafruit can change them to MIT at this date.

**Comment by jepler** [comment]
Though, unlicense is not CC0, they are distinct, hm

**Comment by TheKitty** [comment]
Our Adafruit standard is MIT unless otherwise indicated

**Comment by jepler** [comment]
Licenses updated, ready for review

**Review by TheKitty — APPROVED** [review]
LGTM

**Pull request merged**
