### PR TITLE
Py portal open weather changes

### PR DESCRIPTION
**Pull request by jasonlshelton**
Added day and date on second line of display. Minor adjustment of text placement to account for PyPortal stand

### CODE REVIEW

**Comment by TheKitty** [comment]
@jedgarpark - when you have some free time, would you check this PR? It's been open two years.

**Review by jedgarpark — APPROVED** [review]
These changes look good -- haven't tested on the hardware but they seem totally reasonable.

**Comment by TheKitty** [comment]
@jasonlshelton please resolve merge conflicts and we'll look to merge this. Thanks for your contribution.

**Comment by TheKitty** [comment]
@jepler How do we set this to use the new CI?

**Comment by dhalbert** [comment]
Closing this because the original poster no longer has the repo forked. There are some good changes here, but they could use some rework before merging.

**Pull request closed without merging**
