### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by RichardA1**
Guide code and files for PyPortal User Interface.

### CODE REVIEW

**Comment by TheKitty** [comment]
@RichardA1 - the errors found are at https://travis-ci.com/adafruit/Adafruit_Learning_System_Guides/builds/146860030 - I can look to help you with some of these. Getting indentation set will clear a number of them. And pylint doesn't like variable reuse (i) for whatever reason so I suggest using unique variable names, the garbage collector will save the memory.

**Comment by RichardA1** [comment]
@TheKitty I did all the fixes that I could figure out. There are likely some more 'line-too-long' errors due to the amount of text that fills the Labels but I took care of what I could figure out without breaking the code.

The one thing I do not know how to fix is the 'Using the global statement (global-statement)' from line 267. I can't get things to work correctly without that one.

**Comment by TheKitty** [comment]
I will go in and tweak the code now. The global is valid to us in proper usage, I'll put in statements to tell pylint to ignore this one case.

**Comment by RichardA1** [comment]
Thanks, I am much more of an Arduino code person, but I am trying to get the hang of Cpy. So I am all ears to suggestions on better ways to do this stuff :)

**Comment by TheKitty** [comment]
Richard, you can see what I did in the code. You might try this out to ensure 100% I didn't break anything. I removed some trailing whitespace and used a continuation of line backslash.

**Comment by RichardA1** [comment]
@TheKitty I just tested and there was just a small issue with extra whitespace being added to the strings for display. I fixed and tested that and submitted those changes as another pull request.

Thanks for your help :)

**Pull request merged**
