### PR TITLE
two more demos - for the idf fixed build

### PR DESCRIPTION
**Pull request by ladyada**
cheerlights neopixels + localtime clock display

### CODE REVIEW

**Review by jerryneedell — COMMENTED** [review]
Tested the Cheerlights demo -- works great!
I tried to test the clock demo , but whne I dowload the Helvitica-Bold-100.bdf file it is 4Mbytes and I can't fit it on the MagTag

**Comment by jerryneedell** [comment]
ah -- redownloaded the fonts but now the simpleclock gives
```
 Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 6.0.0-rc.2-260-g231e3d362 on 2020-11-14; MagTag with ESP32S2
>>> import clock
Set background to 16777215
Displaying color
Connecting to AP Needell Airport

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "clock.py", line 19, in <module>
TypeError: unexpected keyword argument 'text_anchor_point'
>>> 
```

**Comment by FoamyGuy** [comment]
@jerryneedell you need the latest version of magtag library that added the text anchoring: https://github.com/adafruit/Adafruit_CircuitPython_MagTag/pull/7

**Comment by ladyada** [comment]
yah i am doing a lot of 'quick n dirty' tests to find bugs

**Review by FoamyGuy — APPROVED** [review]
I successfully tested the SimpleClock script with the build from esp-idf PR
image

**Pull request merged**
