### PR TITLE
Add LittleConnectionMachine project (Pi + CircuitPython)

### PR DESCRIPTION
**Pull request by PaintYourDragon**
Add folder for the “Little Connection Machine” project. Includes 3 Raspberry Pi examples and one for CircuitPython on Pico.

### CODE REVIEW

**Comment by TheKitty** [comment]
There was an issue with another repo under Learn which now has a PR. If yours fails again, wait for #2142 to be merged please.

**Comment by TheKitty** [comment]
Ok, #2142 passed, that should clear up the failed jobs, let's see

**Comment by TheKitty** [comment]
@PaintYourDragon - your branch still has the old file - you'll need to ensure you have the latest files in your repo or close thios PR and make an identical one with the new file that was fixed.

**Comment by PaintYourDragon** [comment]
Merged upstream, still failing. Will close & reopen a new one.

**Pull request closed without merging**
