### PR TITLE
Adding PicoDVI to deps

### PR DESCRIPTION
**Pull request by BlitzCityDIY**
Adding the PicoDVI - Adafruit Fork to the library.deps file

### CODE REVIEW

**Review by TheKitty — APPROVED** [review]

**Comment by BlitzCityDIY** [comment]
@brentru seems like CI is running into something with the Arduino Adafruit IO library and espressif for the QT Py ESP32-S2

**Comment by brentru** [comment]
@BlitzCityDIY  They (Espressif) just released a new BSP (2.0.8) yesterday. I'll look into this.

**Comment by brentru** [comment]
@BlitzCityDIY Similar failure in this CI, but not on AIO, is here: https://github.com/adafruit/Adafruit_Learning_System_Guides/actions/runs/4758334940/jobs/8456260544?pr=2483#step:7:414

Looking into both...

**Comment by brentru** [comment]
@BlitzCityDIY  Maybe worth also including in this PR (untested). C++ expects a string literal (`const char`), so in this sketch, change the following line from: https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/main/EYESPI/Arduino/Color/EYESPI_Test/EYESPI_Test.ino#L568

to 

` const char *label[] = { "X:", "Y:", "Z:" };       // Labels for each axis`

**Comment by BlitzCityDIY** [comment]
@brentru thanks for looking into this. i was wondering if it was the new release. i can test that eyespi change and update the PR

**Comment by brentru** [comment]
Specifically it's https://github.com/espressif/arduino-esp32/pull/7941/

**Comment by brentru** [comment]
@BlitzCityDIY Both pull requests (https://github.com/adafruit/Adafruit_MQTT_Library/pull/222 and https://github.com/adafruit/Adafruit_IO_Arduino/pull/165) to the dependency libraries have been merged and the libraries have been re-released. Please give it a couple of hours to let Arduino pick up the releases, then try re-running this workflow.

If the workflow fails again, please. let me know via this issue.

**Comment by brentru** [comment]
Workflow is passing and @TheKitty  has approved this pull request prior. Merging in.

**Pull request merged**
