### PR TITLE
Add BLE CPB snow globe

### PR DESCRIPTION
**Pull request by caternuson**
Code for JP's BLE CPB Snowtastic Globery.

### CODE REVIEW

**Comment by caternuson** [comment]
more arduino build fail fun :(

**Comment by caternuson** [comment]
what was the trick?

**Comment by ladyada** [comment]
delete the cache - do you have permissions to do that?

**Comment by caternuson** [comment]
yep. just not calibrated on how often that's needed. seems...often?

is there a typical pattern to look for?

**Comment by ladyada** [comment]
if you're able to compile, its not a cache issues
if the core cant be found or a component is missing - thats because a new release came out and the cache is stale

**Comment by ladyada** [comment]
wanna review the cpy GPS PR while you're here? :)

**Comment by caternuson** [comment]
yep

**Pull request merged**
