### PR TITLE
Added FunHouse IOT hub stuff

### PR DESCRIPTION
**Pull request by dherrada**
Adds code and examples for IOT hub guide using dash display

### CODE REVIEW

**Comment by dherrada** [comment]
Should I add disables for the boards failing on the files they're failing on?

**Comment by makermelissa** [comment]
I was trying to disable for my PR, but I couldn't locate the Blink.ino. Sketch that's failing. I think it may be a problem in the nrfutil repo.

**Comment by makermelissa** [comment]
Ok, I figured out why a wild error appeared. Apparently Click was updated to 8.0.0 3 days ago (https://pypi.org/project/click/) and the function that is erroring uses `click.ParamType` (https://github.com/adafruit/Adafruit_nRF52_nrfutil/blob/master/nordicsemi/__main__.py#L59). So don't add disables. I think this needs fixing in nrfutil.

**Comment by makermelissa** [comment]
Based on the Click documentation, I think this may be a bug in Click. Maybe we can anchor to click 7.1.2 for now.

**Comment by makermelissa** [comment]
I think https://github.com/adafruit/Adafruit_nRF52_nrfutil/pull/25 should fix the failures.

**Comment by makermelissa** [comment]
nRF stuff is fixed. I'm not sure why it's failing on Metro M0. Maybe it just needs a re-run.

**Review by ladyada — APPROVED** [review]

**Pull request merged**
