### PR TITLE
first commit doorbell

### PR DESCRIPTION
**Pull request by jedgarpark**
Feather RP2040 + Crickit + Gemmy Animated Eyeball Doorbell with custom audio files and animation.

### CODE REVIEW

**Review by TheKitty — CHANGES_REQUESTED** [review]
There is a pylint error. Also please remove the project name in the SPDX-FileCopyrightText line, only year, your name and for Adafruit Industries please

**Comment by jedgarpark** [comment]
@TheKitty  weird, I'm getting 10.00/10 on pylint. Maybe my pylint is out of date? What errors did it throw?

**Comment by TheKitty** [comment]
Using pylint bin at /opt/hostedtoolcache/Python/3.6.15/x64/bin/pylint
************* Module code
Crickit_Animatronic_Doorbell/code.py 8: standard import "import random" should be placed before "import board" (wrong-import-order)

**Comment by jedgarpark** [comment]
> Using pylint bin at /opt/hostedtoolcache/Python/3.6.15/x64/bin/pylint ************* Module code Crickit_Animatronic_Doorbell/code.py 8: standard import "import random" should be placed before "import board" (wrong-import-order)

@TheKitty  ah, ok I had gotten that error and fixed it, but must not have re-saved before committing. Thanks for the help.

**Review by TheKitty — APPROVED** [review]

**Pull request merged**
