### PR TITLE
NeoPixel Lanyard

### PR DESCRIPTION
**Pull request by firepixie**
Circuit Python Code for Bluetooth Lanyard Project

### CODE REVIEW

**Comment by firepixie** [comment]
I did try the fancyLED animations and they are way too slow.. they look really jerky and bad.  :/  I could maybe try putting solid gradients that don’t animate…?

**Comment by ladyada** [comment]
what about the classic rainbow swirl, also too slow? i haven't done a ton of nrf52840 + LED work. also, what version of circuitpy are  you running?

**Comment by firepixie** [comment]
Yes, even with Rainbow, every time the LEDs refresh at all they sort of blink and stutter. It ends up looking like something cheap from China. I’m running the latest circuitpy (4.0.2).

Honestly this is why I haven’t really delved into Circuit Python yet.. any project with more than 20 LEDs looks awful if you try to animate it.

**Comment by ladyada** [comment]
the only way we can improve is if we experiment. please try 4.1.0 beta, does that improve anything?

**Comment by firepixie** [comment]
I’ll give it a shot!

**Comment by ladyada** [comment]
can be merged once travis passes!

**Comment by ladyada** [comment]
needs a little pylint love! https://travis-ci.com/adafruit/Adafruit_Learning_System_Guides/builds/121317147

**Comment by ladyada** [comment]
hiya you merged before travis passed. please dont do that - wait until it passes and you get the green check

**Comment by firepixie** [comment]
Sorry!  I’ll get this process eventually.  :/

**Comment by ladyada** [comment]
you'll need to immediately fix and submit a new PR for the code with pylint fixed so travis passes, or everyone else's commits will fail. work with mike b if you are not sure how to do that

**Comment by firepixie** [comment]
I did submit a new PR with pylint fixed a few minutes ago, did it come through?

**Comment by ladyada** [comment]
no, travis is still failing on your code
https://travis-ci.com/adafruit/Adafruit_Learning_System_Guides/jobs/221022201#L900

**Pull request merged**
