### PR TITLE
Remove legacy requests.set_socket

### PR DESCRIPTION
**Pull request by justmobilize**
Remove legacy `requests.set_socket` and replace with new `pool` and `ssl_context` helpers from [ConnectionManager](https://github.com/adafruit/Adafruit_CircuitPython_ConnectionManager/)

### CODE REVIEW

**Review by tannewt — COMMENTED** [review]
We'll need someone to check all of the corresponding guides and update them too.

**Comment by justmobilize** [comment]
> We'll need someone to check all of the corresponding guides and update them too.

@tannewt is this something I can do?

**Comment by dhalbert** [comment]
- Should this wait for https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/pull/197 ?

**Review by dhalbert — APPROVED** [review]
Thanks! This looks fine. I will look at the corresponding guides.

**Pull request merged**
