### PR TITLE
Add Cheekmate project (CircuitPython + Arduino)

### PR DESCRIPTION
**Pull request by PaintYourDragon**

### CODE REVIEW

**Review by TheKitty — APPROVED** [review]

**Comment by TheKitty** [comment]
esp32:esp32   2.0.5   /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.5
  In file included from /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/Cheekmate.ino:16:
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   };
   ^
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/work/Adafruit_Learning_System_Guides/Adafruit_Learning_System_Guides/Cheekmate/Arduino/Cheekmate/config.h:76:1: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
  /home/runner/Arduino/libraries/ArduinoHttpClient/src/HttpClient.cpp: In member function 'int HttpClient::startRequest(const char*, const char*, const char*, int, const byte*)':
  /home/runner/Arduino/libraries/ArduinoHttpClient/src/HttpClient.cpp:87:61: error: logical not is only applied to the left hand side of comparison [-Werror=logical-not-parentheses]
               if (!iClient->connect(iServerName, iServerPort) > 0)
                                                               ^
  /home/runner/Arduino/libraries/ArduinoHttpClient/src/HttpClient.cpp:87:17: note: add parentheses around left hand side expression to silence this warning
               if (!iClient->connect(iServerName, iServerPort) > 0)
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   (                                          )
  /home/runner/Arduino/libraries/ArduinoHttpClient/src/HttpClient.cpp:97:64: error: logical not is only applied to the left hand side of comparison [-Werror=logical-not-parentheses]
               if (!iClient->connect(iServerAddress, iServerPort) > 0)
                                                                  ^
  /home/runner/Arduino/libraries/ArduinoHttpClient/src/HttpClient.cpp:97:17: note: add parentheses around left hand side expression to silence this warning
               if (!iClient->connect(iServerAddress, iServerPort) > 0)
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                   (                                             )
  cc1plus: some warnings being treated as errors
  Multiple libraries were found for "WiFi.h"
    Used: /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.5/libraries/WiFi
    Not used: /home/runner/Arduino/libraries/WiFiNINA

**Comment by TheKitty** [comment]
FYI I think const works if you import micropython, Jeff may know more about that

**Comment by PaintYourDragon** [comment]
CI errors are now in an Arduino core library, beyond the scope of my code. What’s the course of action at this point?

**Comment by TheKitty** [comment]
I think this is the true error it's flagging 
image

**Comment by PaintYourDragon** [comment]
Feh…OK…it’s in Espressif’s version of same library. Even if I went and fixed it there, they only issue releases like once a century. Is there an option to punt?

**Comment by TheKitty** [comment]
I think it's time to ask Ladyada to peek

**Comment by brentru** [comment]
The dependency issue has been resolved via https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/2294 but [this PR is running the previous Actions workflow](https://github.com/adafruit/Adafruit_Learning_System_Guides/actions/runs/3176373515/workflow#L38). 

@PaintYourDragon  Merge `adafruit/main` into this PR and commit, adding the new workflow file. Should trigger Actions to run with the updated workflow.

**Pull request merged**
