### PR TITLE
KB2040 code and.... other.

### PR DESCRIPTION
**Pull request by kattni**
A _lot_ of other.

### CODE REVIEW

**Comment by TheKitty** [comment]
image

**Comment by kattni** [comment]
Sigh. Forgot this is using older Pylint. Fixing.

**Comment by kattni** [comment]
Well trying to fix it anyway. It's not failing locally for me. I did what I think might fix it.

**Comment by kattni** [comment]
Whew.

**Comment by kattni** [comment]
@TheKitty Fixed!

**Review by TheKitty — APPROVED** [review]

**Pull request merged**
