### PR TITLE
Activity Generator code

### PR DESCRIPTION
**Pull request by CollinCunningham**
Simple project for CLUE @tannewt or @dhalbert can you review & lemme know?

### CODE REVIEW

**Comment by CollinCunningham** [comment]
@ladyada can you give this a gander? – simple CLUE project for a guide

**Comment by ladyada** [comment]
@CollinCunningham hi i cannot today - @kattni could you please test this on a CLUE? :)

**Comment by kattni** [comment]
@ladyada @CollinCunningham Sure! Will do.

**Comment by CollinCunningham** [comment]
@kattni Good point - I've increased the B button `sleep` accordingly. Should be good to go once it's cleared travis.

**Comment by kattni** [comment]
@CollinCunningham I had to update the branch meaning changes were made while this PR was open. Nothing needs to be done on your end, but it means Travis needs to run again. I'll merge it once everything passes.

**Pull request merged**
