### PR TITLE
remove test code and add more display options

### PR DESCRIPTION
**Pull request by ladyada**
@makermelissa i added precompiled UF2s for testing displays here
https://learn.adafruit.com/adafruit-qualia-esp32-s3-for-rgb666-displays/arduino-rainbow-demo

### CODE REVIEW

**Review by makermelissa — APPROVED** [review]
Looks good for this repo. It appears tests are failing because of Arduino-ESP32 3.0.0-alpha and libraries not being updated yet. See https://github.com/adafruit/ci-arduino/issues/166 for more info.

**Comment by makermelissa** [comment]
I just pushed the latest fixes, so hopefully that will help.

**Comment by TheKitty** [comment]
@makermelissa maybe a .test.only issue? It's picking up other ESP32 boards
image

**Comment by makermelissa** [comment]
@TheKitty they're failing because adafruit-esp32 just released version 3.0.0-alpha1 and @caternuson is going through and fixing the issues.

**Comment by caternuson** [comment]
There's an issue opened here:
https://github.com/adafruit/ci-arduino/issues/166

Although the required changes are in other repos. It's an adventure!

**Pull request merged**
