### PR TITLE
Fixed Scrolling clouds example on CP5

### LINKED ISSUE #910: Error with Circuit Python Flying Toaster
Getting error with flying toaster code. Itsy Bisy M4 running Adafruit CircuitPython 5.0.0-alpha.4 on 2019-09-15; Adafruit ItsyBitsy M4 Express with samd51g19

Using latest library from circuit python bundle adafruit-circuitpython-bundle-5.x-mpy-20191024

`code.py output:
Traceback (most recent call last):
  File "code.py", line 177, in <module>
  File "code.py", line 120, in advance_animation
KeyboardInterrupt: `

@dastels

### PR DESCRIPTION
**Pull request by makermelissa**
Fixes issue 910. (removing link to not auto-close issue).

### CODE REVIEW

**Comment by ladyada** [comment]
yay thanx!

**Comment by djecken** [comment]
Testing code update. Getting a new error in REPL:

`code.py output:
Traceback (most recent call last):
  File "code.py", line 143, in <module>
  File "code.py", line 113, in shift_tiles`

**Comment by makermelissa** [comment]
Huh, that's odd. It's working on mine. I'll have to dig in deeper.

**Comment by djecken** [comment]
OK i tried reflashing cpython 5 alpha 4 for the itsybitsy M4 and downloaded latest libs (bundle 5x 20191029) somewhat new error in REPL:

`Traceback (most recent call last):
  File "code.py", line 138, in <module>
  File "code.py", line 67, in make_tilegrid
  File "adafruit_imageload/__init__.py", line 56, in load
  File "adafruit_imageload/__init__.py", line 47, in load`

**Comment by makermelissa** [comment]
Ok, I'll look into the new error before merging, but it may be related to the imageload library.

**Comment by makermelissa** [comment]
Seems to be all working.

**Pull request merged**
