### PR TITLE
Playing Now Gizmo better stability

### PR DESCRIPTION
**Pull request by makermelissa**
This change has stability improvements. The previous code would occasionally error out after running several hours. I moved the error handling to a smaller block and am using continue instead of pass and have not had it error out since.

### CODE REVIEW

**Comment by ladyada** [comment]
@jedgarpark  please review

**Comment by jedgarpark** [comment]
Oh, @makermelissa I just realized, this is an issue with the library, not your code: https://github.com/adafruit/Adafruit_CircuitPython_BLE_Apple_Media/issues/3
So, other than that, the code seems good to me.

**Comment by makermelissa** [comment]
Ok, cool. Thanks for checking.

**Comment by ladyada** [comment]
@makermelissa @jedgarpark please approve thru github so it can be merged

**Pull request merged**
