### PR TITLE
Add Qualia S3 Factory Reset Source

### PR DESCRIPTION
**Pull request by makermelissa**
Thank you for creating a pull request to contribute to Adafruit's GitHub code!
Before you open the request please review the following guidelines and tips to
help it be more easily integrated:

- **Describe the scope of your change--i.e. what the change does and what parts
  of the code were modified.**  This will help us understand any risks of integrating
  the code.

- **Describe any known limitations with your change.**  For example if the change
  doesn't apply to a supported platform of the library please mention it.

- **Please run any tests or examples that can exercise your modified code.**  We
  strive to not break users of the code and running tests/examples helps with this
  process.

Thank you again for contributing!  We will try to test and integrate the change
as soon as we can, but be aware we have many GitHub repositories to manage and
can't immediately respond to every request.  There is no need to bump or check in
on a pull request (it will clutter the discussion of the request).

Also don't be worried if the request is closed or not integrated--sometimes the
priorities of Adafruit's GitHub code (education, ease of use) might not match the
priorities of the pull request.  Don't fret, the open source community thrives on
forks and GitHub makes it easy to keep your changes in a forked repo.

After reviewing the guidelines above you can delete this text from the pull request.

### CODE REVIEW

**Comment by TheKitty** [comment]
Looks like the PR needs a .test.only file 
https://learn.adafruit.com/submitting-arduino-code-to-the-adafruit-learning-system/adding-a-test-only-file

**Comment by makermelissa** [comment]
It looks like https://github.com/adafruit/ci-arduino/pull/164 needs to be merged first and then it might also fail until https://github.com/espressif/arduino-esp32/pull/8696 is merged.

**Comment by TheKitty** [comment]
It looks like it didn't like the .test.only file 
image

The board is not in the yml file. I noticed the guide was incorrect as someone has been changing up the yml files. The guidance is now correct, the file https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/main/.github/workflows/arduino_cron.yml line 63 will nneed to be edited to include the new board.

**Comment by TheKitty** [comment]
@makermelissa yes, that looks correct also

**Comment by makermelissa** [comment]
Anne, there's actually a lot of hoops needed to be jumped through for it to compile
* It needs to be added to ci-arduino
* Arduino needs to update the arduino-esp32 boards
* The Repo at https://github.com/moononournation/Arduino_GFX needs to make a newer release
* The lib will likely need to be added to https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/main/.github/workflows/arduino_cron.yml after it's released
* The board will need to be added as well like you mentioned.

 Ideally we'd want to skip compiling it for now.

**Comment by TheKitty** [comment]
Ok, are you looking to merge without compile? There is the .none.test.only method but it's a special case.

**Comment by makermelissa** [comment]
Yes, for now. Once some of the other stuff is put in place, we can change it.

**Review by TheKitty — APPROVED** [review]
Approve provisionally per discussion thread, will need CI testing once several other repo PRs are approved & merges

**Comment by makermelissa** [comment]
Ok, I created an issue, which I assigned to myself to add the test back in later.

**Pull request merged**
