### PR TITLE
First commit

### PR DESCRIPTION
**Pull request by TrevKnows**
Adding a Boxing Glove tracker project to the repo

### CODE REVIEW

**Comment by TheKitty** [comment]
Lint results:
image

**Comment by BlitzCityDIY** [comment]
hihi @TrevKnows - you'll want to run pylint on the code.py file. there's instructions in this guide: https://learn.adafruit.com/improve-your-code-with-pylint/install-pylint

**Comment by TrevKnows** [comment]
@BlitzCityDIY Thanks, I've just installed pylint. @TheKitty I'll fix these errors asap

**Comment by TrevKnows** [comment]
@TheKitty Good morning. I was able to get pylint working and have fixed the error you found yesterday. Please review whenever you can.

**Review by TheKitty — APPROVED** [review]

**Pull request merged**
