### PR TITLE
Adding MatrixPortalS3 Flight Proximity Tracker project

### PR DESCRIPTION
**Pull request by TrevKnows**
This project doesn't run. This project has a certificate issue.
https://github.com/adafruit/certificates/issues/3

### CODE REVIEW

**Comment by TheKitty** [comment]
Please add SPDX info for code files https://learn.adafruit.com/submitting-arduino-code-to-the-adafruit-learning-system?view=all

**Comment by TheKitty** [comment]
Pylint messages direct link https://github.com/adafruit/Adafruit_Learning_System_Guides/actions/runs/6853986536/job/18635984210?pr=2659

**Comment by TheKitty** [comment]
image

**Comment by TrevKnows** [comment]
@TheKitty I'm not sure why pylint is raising this error or warning. I've had Liz also take a look at this as well.

**Comment by TheKitty** [comment]
Using regular open, you appear to not be closing the file when done. The with open() syntax will close the file after the while is done. See https://www.freecodecamp.org/news/with-open-in-python-with-statement-syntax-example/ for more.

**Comment by TrevKnows** [comment]
@TheKitty Absolutely - I understand that the file must be closed after opening it, but `OnDiskBitmap` should remain open as long as the bitmap is in use. If I don't do it this way, the icon will not appear. Am I not allowed to use this? `# pylint: disable=consider-using-with`
tempImage6aHiLb

**Comment by TheKitty** [comment]
Tagging in @dhalbert

**Comment by BlitzCityDIY** [comment]
yay! okay looks like the CI issues have been defeated. @TrevKnows as discussed, can you remove the logos that were accessed with the script (keep the "?" graphic in) and then we should be good to merge!

**Pull request merged**
