### PR TITLE
Add code and graphics files for the guide

### PR DESCRIPTION
**Pull request by TheKitty**
https://learn.adafruit.com/quickstart-using-adafruit-eink-epaper-displays-with-circuitpython/

### CODE REVIEW

**Comment by ladyada** [comment]
hiya can we use the existing simpletests?
e.g.
https://github.com/adafruit/Adafruit_CircuitPython_IL0398/blob/master/examples/il0398_simpletest.py

**Comment by TheKitty** [comment]
@ladyada - yes, the text simpletests are nearly identical to the text ones here. I think I tweaked things slightly but I had thoroughly went through the simpletests and they are better now. I'll delete the text examples and point to the simpletests.

**Comment by ladyada** [comment]
ok rad!

**Comment by TheKitty** [comment]
The text examples have been removed from this PR and the display simpletests will be used
https://github.com/adafruit/Adafruit_CircuitPython_IL0373/blob/master/examples/il0373_2.13_color.py
https://github.com/adafruit/Adafruit_CircuitPython_IL91874/blob/master/examples/il91874_simpletest.py

**Comment by ladyada** [comment]
ok do you still need
 EInk_CircuitPython_Quickstart/27_tricolor_eink_shield_bitmap.py 
and the ruler.bmp?

**Comment by TheKitty** [comment]
Crap, I removed the text examples when I should have removed the bitmap examples. I should not have been multitasking with the AIO newsletter. Ok, tweaking yet again.

**Comment by TheKitty** [comment]
Ok, bitmap examples removed for simpletest copies, text examples added back, ruler graphic removed

**Comment by ladyada** [comment]
ok approved once travis passes

**Pull request merged**
