### PR TITLE
delete 2 duplicates

### PR DESCRIPTION
**Pull request by ladyada**
FYI @firepixie

### CODE REVIEW

**Comment by ladyada** [comment]
@firepixie please check your guide still works!

**Comment by firepixie** [comment]
It’s still showing the old incorrect code.  Correct code file is attached.  I don’t know why it’s not working through GitHub.

**Comment by ladyada** [comment]
attachements dont go thru on github, whats the line to look at to know whether its right?

**Comment by firepixie** [comment]
The first two lines should read:

// Code by Erin St. Blaine for Adafruit Industries
// Color Touch Pendant Tutorial: https://learn.adafruit.com/color-touch-pendant-necklace/introduction

**Comment by ladyada** [comment]
@jwcooper heya do you know how long it takes for the github-embed cache to pick up changes?

**Comment by kattni** [comment]
@ladyada I've had it take a couple of hours before. I glanced at the guide and, if I'm looking in the correct place, it looks like the code is showing the first two lines that Erin said it should be. 

A way to verify if the embed link is correct is to click on "View on Github" above the code in Learn - if it takes you to the correct file, then Learn is caching the previous version and it should eventually update.

**Pull request merged**
