### PR TITLE
Moved pulseio.PWMOut to pwmio.PWMOut

### PR DESCRIPTION
**Pull request by dherrada**
Most of the uses were in this repo so I decided to do it first

### CODE REVIEW

**Review by tannewt — COMMENTED** [review]
Code looks good. Let's wait for https://github.com/adafruit/Adafruit_Blinka/issues/402 though. We'll also want to update any guide text that talks about pulseio for these.

**Comment by brentru** [comment]
@dherrada  I moved the metrox examples into this library after you created this PR. Do you want me to check out another PR for updating the metrox example to PWMIO (https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/master/MetroX_CircuitPython/mib_colorful_light.py) or would you want to add it to this PR?

**Comment by tannewt** [comment]
FYI Blinka 6.0.1 has `pwmio` now. So, this can be merged after @brentru's comment is addressed.

**Review by jepler — APPROVED** [review]
Let's get this merged and file a fresh issue about the remaining lib that is not covered.

**Pull request merged**
