### PR TITLE
CircuitPython displayio examples

### PR DESCRIPTION
**Pull request by caternuson**
CircuitPython displayio examples to go with Learn guide.

### CODE REVIEW

**Comment by ladyada** [comment]
u can merge once travis passes

**Comment by caternuson** [comment]
ok. wait..wasn't i suppose to ping you?

**Comment by ladyada** [comment]
for what?

**Comment by caternuson** [comment]
so you'd see this PR :)

**Comment by ladyada** [comment]
ok yah i reviewed, so you dont need to ping, just merge once passing!

**Pull request merged**
