### PR TITLE
added CP files for CPX Treasure Hunt

### PR DESCRIPTION
**Pull request by caternuson**
CircuitPython files for this guide:
https://learn.adafruit.com/circuit-playground-treasure-hunt

### CODE REVIEW

**Comment by ladyada** [comment]
code looks good, dya want to just have one treasure with a note to configure the id?

**Comment by caternuson** [comment]
Sure. Note = code comment? Or something else?

**Comment by ladyada** [comment]
yeah lik CHANGE THIS NUMBER TO 2, 3, ETC, A UNIQUE NUMBER FOR EACH TREASURE! 😁
also call it out in the guide , i think you did tho, i don’t have it pulled up

**Comment by caternuson** [comment]
did both in the guide. said you can change it, but then gave them the ready-to-go versions.

**Comment by ladyada** [comment]
cool

**Pull request merged**
