### PR TITLE
MagTag Christmas Countdown: Update for CP7

### PR DESCRIPTION
**Pull request by lesamouraipourpre**
Remove max_size usage with displayio.Group
Update OnDiskBitmap filename string usage for CP7

Ref: https://github.com/adafruit/Adafruit_Learning_System_Guides/issues/1603

Learn Guide: https://learn.adafruit.com/magtag-daily-christmas-countdown
Updates needed:
Page: https://learn.adafruit.com/magtag-daily-christmas-countdown/circuitpython-code-walkthrough
Sections:
* https://learn.adafruit.com/pages/21083/elements/3078956/download
* https://learn.adafruit.com/pages/21083/elements/3078958/download

### CODE REVIEW

**Comment by TheKitty** [comment]
@lesamouraipourpre - please tag me as reviewer on these CP 7 update PRs. Thanks!

**Comment by lesamouraipourpre** [comment]
> @lesamouraipourpre - please tag me as reviewer on these CP 7 update PRs. Thanks!

The links to request a reviewer don't appear for me. However, I can mention you in the description if that's OK.

**Review by TheKitty — APPROVED** [review]
Looks good

**Comment by TheKitty** [comment]
Changed Guide to match code changes

**Pull request merged**
