### PR TITLE
PyPortal Smart Lighting Controller

### PR DESCRIPTION
**Pull request by brentru**

### CODE REVIEW

**Comment by ladyada** [comment]
you can merge once travis passes!

**Comment by brentru** [comment]
@ladyada  Pylint passes but travis seems to be failing on Arduino .ino files, which aren't included in this pull request? 

https://travis-ci.com/adafruit/Adafruit_Learning_System_Guides/jobs/189797420#L666
https://travis-ci.com/adafruit/Adafruit_Learning_System_Guides/jobs/189797420#L788

**Comment by ladyada** [comment]
that happens when arduino cache needs to b e cleared (there's a new SAM library version or something went weird with the cache) - you can clear it yourself and re-kick travis

**Comment by brentru** [comment]
Done, cache has been cleared and build is passing. Merging in...

**Pull request merged**
