### PR TITLE
Update PyPortal_MQTT_Control

### PR DESCRIPTION
**Pull request by brentru**
Relevant Issue: https://github.com/adafruit/Adafruit_Learning_System_Guides/issues/1110

Updating PyPortal_MQTT_Control to reflect the latest version of [the MiniMQTT library](https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/).

Note: This code is untested. The guide's (https://learn.adafruit.com/pyportal-mqtt-sensor-node-control-pad-home-assistant/code-breakdown) code walkthrough page does not reference this method signature and does not need an update.

### CODE REVIEW

**Comment by ladyada** [comment]
@RichardA1 hihi wanna test this updated code?

**Comment by RichardA1** [comment]
Ah, yes I should be able to get the PyPortal out and test it today.

**Comment by ladyada** [comment]
@RichardA1 hihi - dya have any cycles to test out this code fix? :)

**Comment by brentru** [comment]
@RichardA1  Have you been able to test this patch?

**Comment by TheKitty** [comment]
@RichardA1 Have you been able to test this patch?

**Comment by RichardA1** [comment]
Yeah, I tested it out and it worked.

**Pull request merged**
