### PR TITLE
Edidtester

### PR DESCRIPTION
**Pull request by ladyada**
by request https://pinafore.social/statuses/110588425628384190

### CODE REVIEW

**Comment by dhalbert** [comment]
@ladyada I haven't tested but if this is still relevant, will approve and merge

**Comment by ladyada** [comment]
ok i added spdx and removed the ruxpin stuff htat never worked well

**Comment by dglaude** [comment]
This blog post ( https://blog.adafruit.com/2023/05/26/teddy-ruxpin-hacking-%F0%9F%A7%B8%F0%9F%93%9A%F0%9F%8E%B6%F0%9F%97%A3%EF%B8%8F%F0%9F%A4%96/ ) is referencing this place ( https://github.com/ladyada/Adafruit_Learning_System_Guides/tree/main/Teddy_Ruxpin ) that does not exist (anymore?) and is not merged here and not on @ladyada fork. I'll send a mail to support@adafruit because it is sad to have a blog post with dead link.

I would love to know about the better solution, I plan to put halloween scary image in the eye of my ruxpin.

**Comment by ladyada** [comment]
https://learn.adafruit.com/teddy-ruxpin-rebuild/building-a-new-story-file

**Comment by dglaude** [comment]
Thanks, I did not notice the code of adafruit/snxrom was also taking care of the eye images, because the guide does not talk about it. Also I already reported an issue there.

I will be working to try to make it work for me and maybe help document the process.

**Pull request merged**
