### PR TITLE
Simplify per Ladyada

### PR DESCRIPTION
**Pull request by TheKitty**
Remove code using lists

### CODE REVIEW

**Comment by ladyada** [comment]
perfect! can merge when linted!

**Comment by caternuson** [comment]
looks like you're having the same fun i am in #928 
somethings up with the arduino checks. it's not a linter issue.

**Comment by ladyada** [comment]
@caternuson @TheKitty what do you think we should do first to try and resolve

**Comment by caternuson** [comment]
I'm not sure. I've gone down the rabbit hole a little bit, but admit I don't understand what has changed. For the last build that passed, the ESP32 install looked like this:
https://travis-ci.com/adafruit/Adafruit_Learning_System_Guides/builds/136090992#L478
but on these recent fails, it's hiccuping, here's @TheKitty 's:
https://travis-ci.com/adafruit/Adafruit_Learning_System_Guides/builds/136225067#L483
Here's mine from #928 :+1: 
https://travis-ci.com/adafruit/Adafruit_Learning_System_Guides/builds/136212385#L478

So something around here?
https://github.com/adafruit/travis-ci-arduino/blob/master/install.sh#L99

**Comment by ladyada** [comment]
did you try deleting the travis cache

**Comment by TheKitty** [comment]
@ladyada - yes, that's what I did when it first occurred.

**Comment by caternuson** [comment]
And I just tried it again. Still same:
https://travis-ci.com/adafruit/Adafruit_Learning_System_Guides/builds/136212385#L483

**Comment by ladyada** [comment]
https://github.com/espressif/arduino-esp32/issues/3475

**Comment by ladyada** [comment]
i think they will fix very soon!

**Comment by caternuson** [comment]
@ladyada yah, that was it. thanks for finding that. seems to be all good now.

@TheKitty i went ahead and restarted your build(s)

**Comment by TheKitty** [comment]
Thank you @ladyada @caternuson

**Pull request merged**
