### PR TITLE
Burning Fire Wizard Staff Code

### PR DESCRIPTION
**Pull request by firepixie**
added project .zip file

### CODE REVIEW

**Comment by kattni** [comment]
@ladyada The linter is failing on code unrelated to this PR. The code in this PR is now passing.
```
Using config file /home/travis/build/adafruit/Adafruit_Learning_System_Guides/.pylintrc
************* Module code
NeoPixel_Badge_Lanyard/code.py 114: Trailing whitespace (trailing-whitespace)
------------------------------------
Your code has been rated at 10.00/10
The command "./pylint_check" exited with 123.```

**Comment by ladyada** [comment]
@kattni ok please also fix that py file in this commit

**Comment by kattni** [comment]
@ladyada The trailing whitespace in the badge lanyard code was added within this PR. I noticed this finally after trying to figure out how to PR to this PR. Fix is made in this PR.

@firepixie Please make sure when you create a PR that the files included are only the files you intend to include in the PR. Somehow a space was added to another file and submitted as a change with this PR.

**Comment by ladyada** [comment]
huzzah great teamwork :) thanks for the fix @kattni

**Pull request merged**
