### PR TITLE
IR learning guides have ones and zeros swapped

### PR DESCRIPTION
**Pull request by bradanlane**
There are several CircuitPython learning guides related to IR. When tested them, they produced "2's compliment" results. I discovered the transmit examples had reversed the values for a "0" vs a "1".

To verify, my observation, I reviewed the sample code from the irremote CircuitPython library. The library code has the correct values for "0" and "1".

This pull request makes that corrections for the learning guides.

The learning guide changes were run on a Raspberry Pi PICO with the Adafuit IR Emitter module and the IR Receiver module

### CODE REVIEW

**Review by dhalbert — APPROVED** [review]
This looks good. It essentially completes the corrections done by @tkomde in https://github.com/adafruit/Adafruit_CircuitPython_IRRemote/pull/68 and https://github.com/adafruit/Adafruit_CircuitPython_IRRemote/pull/69.

I'll review the guides text and change as needed.

**Review by dhalbert — CHANGES_REQUESTED** [review]
Some discord discussion: the library uses `560` instead of `550` and its header values are `[9000, 4500]`. @bradanlane will retest.

**Comment by bradanlane** [comment]
As suggested by @dhalbert, the IR Transmit learning examples have been updated to use header pulses of 9000,4500 and a mark pulse of 560.

Testing was done using the Raspberry Pi PICO with the Adafruit IR emitter and IR Receiver modules. Testing on Circuit Plaground Express was not conducted as I do not have hardware.

**Comment by bradanlane** [comment]
embarrassing copy/paste error

**Review by dhalbert — APPROVED** [review]
Thank you for this, and your patience.

**Pull request merged**
