### PR TITLE
Crank USB hid code

### PR DESCRIPTION
**Pull request by djecken**
Crank USB hid code

### CODE REVIEW

**Comment by ladyada** [comment]
how is this code different than the media dial from before?

**Comment by djecken** [comment]
just the neopixel time code has been stripped out.

**Comment by djecken** [comment]
also it's config'd for the wiring on ItsyBitsy M0

**Comment by ladyada** [comment]
i think maybe best to just use the same code, leave neopixel unconnected, and at the top have some commented out lines for whichever they want to use, then?

**Comment by djecken** [comment]
sure i can add that back. btw, this code was not in learn repo - only embed in the media dial guide.

**Comment by ladyada** [comment]
ok then lets add that code in, and you can adjust it!

**Pull request closed without merging**
