### PR TITLE
Firewalker Lite arduino code for Gemma M0

### PR DESCRIPTION
**Pull request by firepixie**
Works with Gemma M0

### CODE REVIEW

**Comment by ladyada** [comment]
dont forget the .test.only file - do you know how to do that?

**Comment by firepixie** [comment]
Nope.

**Comment by ladyada** [comment]
ok see it here
https://github.com/adafruit/Adafruit_Learning_System_Guides/tree/master/GemmaM0_Band_Jacket/DiscoBandCamp

**Comment by firepixie** [comment]
OK I see the file, it appears to have nothing in it. Sorry I’m still not sure what you need me to do..

Also I saw that my code failed checks, so I updated it and removed the Serial references, since they weren’t needed. I can do another PR but I want to get this in file there too before I do that. Do I just make a blank text file and call it .gemma_m0.test.only ?

**Comment by caternuson** [comment]
> Do I just make a blank text file and call it .gemma_m0.test.only ?

Yep. That's it. It's just a flag for the automated stuff that runs.

Also, you can commit and push changes to this same PR if you want. No need for a new PR. The updates will show up here and the automated stuff will re-run, etc.

yah - like that! you just pushed a commit right as I was writing this :)

**Comment by firepixie** [comment]
OK I added that and updated the code, but still got a “failed” message (though it passed for the Gemma m0). Is there anything else I need to do?

**Comment by caternuson** [comment]
> Is there anything else I need to do?

Nope. You're passing now :)

FYI - The `.gemma_m0.test.only` file wasn't blank. Probably a text editor thing.

**Comment by firepixie** [comment]
You fixed it? I used textedit on my mac and it sure didn’t like me for it.

Thanks!

**Comment by caternuson** [comment]
I didn't. Not sure it really matters. I *think* the check is only for file existence. Contents don't matter. Just for future ref.

**Comment by ladyada** [comment]
thank you! good work erin - i was in meetings till now. we can merge :)

**Review by ladyada — APPROVED** [review]

**Pull request merged**
