### PR TITLE
Uploading MIDI guitar code

### PR DESCRIPTION
**Pull request by BlitzCityDIY**
Code for MX MIDI Guitar learn guide

### CODE REVIEW

**Comment by ladyada** [comment]
yay please tag me once its linted :)

**Comment by djecken** [comment]
Looks like the code is rated 10/10 but build is failing. Could it be from the spaces in the folder name? ("MX MIDI Guitar" rename to "MX_MIDI_Guitar")

**Comment by djecken** [comment]
Tested code running Adafruit CircuitPython 5.0.0-rc.0 on 2020-02-26; Adafruit Grand Central M4 Express with samd51p20. Very solid strumming now, awesome work @BlitzCityDIY ! :-)

**Comment by BlitzCityDIY** [comment]
yay! thanks @djecken ! ohh spaces.. should I close and try a new PR?

**Comment by djecken** [comment]
OK I think you can just update the folder name and push that into this PR.

**Pull request merged**
