### PR TITLE
Add/update DotStar single LED template code

### PR DESCRIPTION
**Pull request by kattni**
Tested on ItsyBitsy M4.

### CODE REVIEW

**Comment by PaintYourDragon** [comment]
With a single LED and with auto_write being the default case, would it be OK to replace:
```
        for led in range(1):
             dot_index = (led * 256 // 1) + color_value
             dot[led] = colorwheel(dot_index & 255)
         dot.show()
```
with:
```
        dot[0] = colorwheel(color_value)
```
?

Sometimes there’s Learning Value in showing things the verbose way, so no worries if that was the intent.

**Comment by kattni** [comment]
@PaintYourDragon Ooh, this is good. I don't need it to be verbose. I will need to update the copy to match it, but it means less copy. In this case, it's simply meant to give rainbows, not necessarily explain how rainbows work deep down. To be clear, you're saying the function should look like this? Or am I missing part of your suggestion?
```
def rainbow(delay):
    for color_value in range(255):
        dot[0] = colorwheel(color_value)
        dot.show()
        time.sleep(delay)
```

**Comment by PaintYourDragon** [comment]
Yep. All the math just distills down to nothing in that case and color_value can be passed straight to colorwheel. And the show() call might be redundant.

**Comment by kattni** [comment]
Wait - I just figured out what I was missing. I never set `auto_write=False`. Removing the `show()`!

**Review by TheKitty — APPROVED** [review]

**Pull request merged**
