### PR TITLE
Updated Google Calendar example to make better use of MagTag library

### PR DESCRIPTION
**Pull request by makermelissa**
This fixes the learn guide code so it no longer fails in CircuitPython 7 by making better use of the MagTag library, which avoids duplicate conflicting network objects.

### CODE REVIEW

**Comment by makermelissa** [comment]
Tagging @brentru as reviewer in case the Learn guide needs to be updated before this is merged.

**Review by TheKitty — APPROVED** [review]

**Comment by brentru** [comment]
@makermelissa  Should the PyPortal Google Calendar project also get modified? (https://learn.adafruit.com/pyportal-google-calendar-event-display)

**Comment by makermelissa** [comment]
@brentru yes, I think so.

**Comment by makermelissa** [comment]
I'll submit as a separate PR.

**Review by brentru — APPROVED** [review]
Read through code, compared to guide's Usage Page (nothing needs to be changed).

I'll change some code and text within the walkthrough, but LGTM.

**Pull request merged**
