### PR TITLE
simplify ble_crickit_light_switch.py

### PR DESCRIPTION
**Pull request by dhalbert**
This simplifies the code, removing `advertising_now` and removing moving the server one degree at a time. That code was there from the CircusPython to move the servo more slowly and to call `sparkle()` as continuously as possible. It's not necessary here.

The Learn Guide will need a tiny update to remove the sentence saying the servo is moved one degree at a time.

### CODE REVIEW

**Comment by dhalbert** [comment]
Tested with a servo, and tested that it can be disconnected and reconnect.

**Comment by jedgarpark** [comment]
This no longer functions as it did with the anticipation of the action and neutral centering.

**Comment by dhalbert** [comment]
Sorry, I misunderstood how this worked. Pushed another commit so it now returns to neutral after a brief delay to make sure the servo has gone all the way to the up or down position. You may want to increase the delay if needed.

The main point of this was to remove the 1-degree stepping, which was just there for `sparkle()`. The `advertising_now` logic was also due to `sparkle()`. I'm trying to make sure the canonical examples are as simple as possible.

**Comment by jedgarpark** [comment]
Hmm, this version seems to only make the servo twitch a little bit in one direction and nothing in the other.

**Comment by jedgarpark** [comment]
Oh, and I totally agree that the example shouldn't have the left over remains of the sparkle stuff, just want to get it working the way I had it from a functional standpoint.

**Comment by dhalbert** [comment]
Ugh, that version was not pushed properly: it was missing a `time.sleep()`. Sorry about wasting your time on this. Try the latest version now.

**Comment by jedgarpark** [comment]
Haha, who is Charlie Brown in this scenario ... :)

**Comment by jedgarpark** [comment]
That's version is better, but it doesn't start with the anticipation motion that I had in the original. Sorry to be a pain about this, but I really loved the way it moved.

**Pull request merged**
