### PR TITLE
Update for new displayio APIs

### PR DESCRIPTION
**Pull request by FoamyGuy**
Looking to get feedback from the wider team before making this adjustment on a larger scale across all examples.

A few points I'm interested in hearing ideas on:

 - Do we want to provide commented old version for some period of time for people that are still using <= 7.X versions?
 - Should there be different wording for either of the comments? Perhaps trying to get away from using the "show" verb for the new one so our language matches the API?

### CODE REVIEW

**Comment by tannewt** [comment]
We discussed this in yesterday's meeting and decided to wait on these updates until 8 is more stable and we've stopped the 7.x bundle.

**Comment by FoamyGuy** [comment]
Closing this for now. We can re-open or create new ones when the time comes.

**Comment by FoamyGuy** [comment]
Discussed again in the weeds 10/2/23.

The plan is to start working on these changes after the 7.x bundle is finalized

**Comment by caternuson** [comment]
In terms of comments and showing old version,etc. - consensus from meeting was NO to this. Just change `show()` to `root_group =`.

**Comment by FoamyGuy** [comment]
closing in favor of https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/2647

**Pull request closed without merging**
