### PR TITLE
Pedantic grammar fix

### PR DESCRIPTION
**Pull request by IrregularShed**
You don't have a possessive apostrophe following _it_ (see http://www.sussex.ac.uk/informatics/punctuation/apostrophe/possessives )

### CODE REVIEW

**Comment by ladyada** [comment]
what's weird is if you say something belongs to susan, you write "susan's" but if something belongs to an item, its not "it's"
this always bugged me.

**Comment by ladyada** [comment]
thanks :)

**Comment by IrregularShed** [comment]
It's daft, isn't it? As a fresh-faced teenager in the early 90s I was writing for a magazine and got schooled by my editor (who ended up teaching me pretty much everything to do with writing) so I've spent over quarter of a century wincing when I see grammatical errors 😁

**Comment by ladyada** [comment]
we're happy to take any grammatical / spelling fixes! we write fast, so errors do crop up :)

**Pull request merged**
