### PR TITLE
Bug fixes and snooze tweaks

### PR DESCRIPTION
**Pull request by dastels**

### CODE REVIEW

**Comment by ladyada** [comment]
@djecken please try out these rev's from dave till you say its good to ship :)

**Comment by dastels** [comment]
Fixed snooze behaviour and made some other improvements.

**Comment by djecken** [comment]
@dastels the alarm state seems to stop working after two alarm events have been triggered. a reset is needed to get it working again.

**Comment by dastels** [comment]
How do I replicate it? I have an idea what it might be.

Dave

**Comment by djecken** [comment]
Start by setting the alarm a minute ahead of the current time and tap screen to clear it. Then update the alarm a minute ahead, wait and clear again. repeat a second time, try a third. The alarm stops triggering on the next update.

**Comment by djecken** [comment]
This is good to merge in @TheKitty

**Comment by TheKitty** [comment]
Merged @djecken @dastels

**Pull request merged**
