### PR TITLE
Made changes to projects to have them work with MagTag project selector

### PR DESCRIPTION
**Pull request by dherrada**
pretty much just moving bmps into the bmps/ directory and fonts into the fonts/ directory and updating the paths.

### CODE REVIEW

**Review by ladyada — APPROVED** [review]

**Comment by dherrada** [comment]
@ladyada Would you like me to update screenshots in the guides this change affects to reflect the changes?

**Comment by ladyada** [comment]
yes please!

**Comment by dherrada** [comment]
I've tested all of these on the magtag selector project, so I have no reason to believe they wouldn't work by themselves, but I'm going to test them when I'm getting the updated screenshots and then merge it once that's done

**Comment by ladyada** [comment]
ok!

**Comment by dherrada** [comment]
@ladyada Everything has been tested and the wording and pictures in some of the guides have been updated

**Pull request merged**
