### PR TITLE
Update PyPortal User Interface code to support Titano

### PR DESCRIPTION
**Pull request by aioue**
- **Describe the scope of your change--i.e. what the change does and what parts
  of the code were modified.**  This will help us understand any risks of integrating
  the code.

Fixes blank screen/barely legible text on Titano. Without these changes the code *appears* to not function on a Titano which is confusing for newbies.

- **Describe any known limitations with your change.**  For example if the change
  doesn't apply to a supported platform of the library please mention it.

Does not address PyPortal Pynt.

- **Please run any tests or examples that can exercise your modified code.**  We
  strive to not break users of the code and running tests/examples helps with this
  process.

Tested on Titano.

### CODE REVIEW

**Comment by ladyada** [comment]
@RichardA1 take a look!

**Review by FoamyGuy — APPROVED** [review]
Looks good to me. Thanks for adding support for Titano @aioue 

Tested successfully on PyPortal Titano

**Comment by CedarGroveStudios** [comment]
@FoamyGuy @aioue Discovered the source of the Titano brightness problem. The LED current controller on the board is being driven by a PWM signal with a frequency that is outside of the linear response range of the controller. Here's the issue:

https://github.com/CedarGroveStudios/Cat/issues/1

Not sure how to post an issue in `displayio.display` in the core for the fix.

**Comment by dhalbert** [comment]
> Not sure how to post an issue in `displayio.display` in the core for the fix

Thanks for figuring it out! Submit an issue to https://github.com/adafruit/circuitpython/issues, or submit a PR to circuitpython.

**Comment by FoamyGuy** [comment]
@CedarGroveStudios interesting. Thanks for hunting that down! An issue for the core can be created here: https://github.com/adafruit/circuitpython/issues

I wonder if there is any practical downside to just lowering the frequency inside the core for all displays.

**Comment by dhalbert** [comment]
> I wonder if there is any practical downside to just lowering the frequency inside the core for all displays.

500 Hz should not have any noticeable flicker. It should be tested on at least some boards. I wonder if a lower frequency can get into audio channels, though, and cause a background tone. Perhaps that was the reason for the high frequency choice.

**Comment by CedarGroveStudios** [comment]
@FoamyGuy Don't think there'll be an issue with other displays since, in most cases, it's just controlling a small array of backlight LEDs. 

I tried it on the TFT FeatherWings with no issues. No flicker, no annoying buzz. I'll give it a shot on some other backlit displays that are hanging around the workbench. The `pwmio` default frequency of 500Hz seems to be the sweet spot.

Fixing it for built-in displays in `displayio.display` is a one-line change, I think. I'll look at breakout board drivers in the library to see if they will need changes.

**Comment by CedarGroveStudios** [comment]
> > I wonder if there is any practical downside to just lowering the frequency inside the core for all displays.
> 
> 500 Hz should not have any noticeable flicker. It should be tested on at least some boards. I wonder if a lower frequency can get into audio channels, though, and cause a background tone. Perhaps that was the reason for the high frequency choice.

Good point. I don't have a way to test the potential interaction on the PyPortal without modifying the core, something that's outside of my wheelhouse.

**Comment by dhalbert** [comment]
If you open an issue with the fix, we can easily make a PR and make a build. You are the right expert to do the audio testing.

**Comment by CedarGroveStudios** [comment]
> If you open an issue with the fix, we can easily make a PR and make a build. You are the right expert to do the audio testing.

I'm not certain that I picked the right parameter in `displayio.display` #119, but will create an issue after today's meeting.

**Comment by CedarGroveStudios** [comment]
submitted as https://github.com/adafruit/circuitpython/issues/6236

**Pull request merged**
