### PR TITLE
Update Tides code to support PyPortal Titano

### PR DESCRIPTION
**Pull request by aioue**
**Describe the scope of your change--i.e. what the change does and what parts
  of the code were modified.**  This will help us understand any risks of integrating
  the code.

- Add Titano scaled version of the background image
- Locate Time string at x coord suitable for Titano screen

**Describe any known limitations with your change.**  For example if the change
  doesn't apply to a supported platform of the library please mention it.

Does not render graph curves (see youtube video in comment), bug in original Admiralty code? Would appreciate review from author.

### CODE REVIEW

**Comment by aioue** [comment]
[Recorded what the graphical Admiralty code looks like on the Titano](https://youtu.be/kV8-ZJNLm4Q).

**Comment by caternuson** [comment]
oops. sry. missed this somehow.

@aioue It looks like the plotting didn't work maybe? Why only a couple of dots?
image

**Comment by aioue** [comment]
@caternuson yes I don't know why it doesn't plot the line. All the PR does is expand the background image to fit on a higher res titano.

**Comment by caternuson** [comment]
In theory, the plotting should also scale, since it bases things on actual display width and height.

Can you try adding a print out of the actual tide data to see what it looks like?
```python
    if current_time.tm_yday != current_yday:
        # new day, time to update
        tide_data = get_tide_data()
        print(tide_data)    # DEBUG output
```

**Comment by aioue** [comment]
Add two debug statements at end of `get_tide_data()` (on top of existing PR):

```python
    # Convert raw data to display coordinates
    for data in raw_data:
        _, t = data["DateTime"].split("T") # date and time
        t = '{:.5}'.format(t)
        h, m = t.split(":")         # hours and minutes
        v = data["Height"]               # water level
        x = round( (WIDTH - 1) * (60 * float(h) + float(m)) / 1440 )
        y = (HEIGHT // 2) - round(VSCALE * float(v))
        y = 0 if y < 0 else y
        y = HEIGHT-1 if y >= HEIGHT else y
        new_tide_data[x] = y
        print("Processed data element...")    # DEBUG output

    print(new_tide_data)    # DEBUG output
```

Output:
<details>
<summary>Click to see code output</summary>

```
Retrieving data...Reply is OK!
Processed data element...
Processed data element...
Processed data element...
Processed data element...
[None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 138, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 85, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 147, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 85, None, None]
```
</summary>

**Comment by caternuson** [comment]
Lots of `None` results. That'd explain why the plot is not working. But not sure why those are ending up as `None`.

Is the base value bad for some reason? Try printing out what it's getting for the `Height` value:
```python
        v = data["Height"]               # water level
        print("v =", v)
```

**Comment by aioue** [comment]
Output:
```bash
Retrieving data...Reply is OK!
v = 0.398293
Processed data element...
v = 2.57726
Processed data element...
v = 0.573809
Processed data element...
v = 2.6919
Processed data element...
```

I'm using a free API key for [UK Tidal API - Discovery](https://admiraltyapi.portal.azure-api.net/products/uk-tidal-api). Listed as "current plus 6 days’ worth of tidal events". That should be enough data?

**Comment by caternuson** [comment]
The free API should be fine. Only the current day data is needed.

It only returned 4 data points for some reason. Not a full day's worth of data. So that seems to be where it's breaking.

Is the non-Titano version of the code running OK for your setup and location?

**Comment by aioue** [comment]
If I load [the raw original file](https://raw.githubusercontent.com/adafruit/Adafruit_Learning_System_Guides/main/PyPortal_Tides/admiralty_tides_graphical/code.py), I get 4 data points, and no curve. Makes me realise what a blurry job I did of expanding the original background!

**Comment by caternuson** [comment]
@aioue hey, general ping, are you still watching this thread?

**Comment by aioue** [comment]
> @aioue hey, general ping, are you still watching this thread?

Yes occasionally! I'm a little busy but would have time to test some changes every week or so.

**Comment by caternuson** [comment]
OK, just wondering if you've been able to figure out why you're only getting 4 data points back from the API query for tide data?

**Comment by aioue** [comment]
I didn't figure it out. It happened with multiple locations from the same source (Admiralty API).

**Comment by aioue** [comment]
@caternuson my trial API access has expired and they want a large sum to renew. Could we get this update to the original code agreed and merged in and work on fixing the admiralty issue separately please? I'm not modifying any API calls, just getting the display working on the Titano.

**Comment by caternuson** [comment]
OK. Will just merge as is. Perhaps is has something to do with data returned for those specific locations? Can make this live and others can try the code on Titano and maybe that will help provide more info on what's going on.

**Review by caternuson — APPROVED** [review]

**Pull request merged**
