### PR TITLE
Start a new repo for Dano's Walking Stick Guide

### PR DESCRIPTION
**Pull request by TheKitty**

### CODE REVIEW

**Comment by caternuson** [comment]
Will `step_col` and `audio_file` ever be expanded? They both only contain a single entry and the index used is hardwired. So these could just become simple constants. Or, if there is a plan to allow more entries - how will they be added? This would lead to choice between list vs. tuple.

**Comment by TheKitty** [comment]
@danowall see above

**Comment by TheKitty** [comment]
> Will `step_col` and `audio_file` ever be expanded? They both only contain a single entry and the index used is hardwired. So these could just become simple constants. Or, if there is a plan to allow more entries - how will they be added? This would lead to choice between list vs. tuple.

Dano is hoping that as is it's a starting point for beginners to look at adding more than one music file, etc.

I suggest approving as-is if possible

**Comment by caternuson** [comment]
OK. It's definitely functional as is.

**Pull request merged**
